### PR TITLE
[LD-6229] removes monitoring for hamburger dynamodb tables

### PR DESCRIPTION
**Pull request by MehdiZonjy**
- Configures instana agent to drop monitoring for Hamburger Dynamodb tables
- I've upgrading the instance to t2.medium awhile back but forgot to reflect the change in CF

### CODE REVIEW

**Comment by aquila-droid** [comment]
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/trainingrocket/stacks/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [b35951e](https://github.com/trainingrocket/stacks/commits/b35951e5c302b1112da33dba1c81338a4cb8b1ba) [LD-6229] removes monitoring for hamburger dynamodb tables

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **naiduarvind**
You can assign the PR to them by writing `/assign @naiduarvind` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
LGTM label has been added.  <details>Git tree hash: a513860f1a789cd37f8a2eacc3512515066cef29</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#issuecomment-527330314" title="LGTM">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#issuecomment-527330352" title="Approved">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#pullrequestreview-282791663" title="Approved">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by naiduarvind** [comment]
@MehdiZonjy - you are missing the signed commits.

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#issuecomment-527330352" title="Approved">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#issuecomment-527330352" title="Approved">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/stacks/pull/9#pullrequestreview-282802325" title="Approved">naiduarvind</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fstacks).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/stacks/blob/master/OWNERS)~~ [naiduarvind]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
